# Generated by Django 5.1.2 on 2025-02-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="nationality",
            field=models.CharField(
                blank=True,
                choices=[("USA", "Estados Unidos"), ("BRA", "Brasil")],
                max_length=100,
                null=True,
            ),
        ),
    ]
